from . import help
from . import start
from . import test_solution
from . import settings
from . import results
from . import referal
from . import admin
from . import no_active_tests_admin
from . import active_tests_admin
from . import add_test
from . import change_test
from . import echo
